---
namespace: "spatiumcepa"
name: "truenas"
version: "0.0.1"
description: Spatium Cepa TrueNAS Management Ansible Collection
readme: "README.md"
authors:
  - Nicholas Kiraly (@nkiraly)
dependencies: {}
license:
  - "BSD-2-Clause"
tags:
  - platform
repository: "https://github.com/spatium-cepa/ansible-collection-spatiumcepa-truenas"
